[package]
name = "cal"
version = "0.1.0"
authors = ["pandanoir <moon_in_france@yahoo.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
colored = "2.0.0"
getopts = "0.2"

